from cx34 import cx34
hp = cx34(1,"/dev/ttyUSB0", 5)
hp.temperature_units='F'

print(f"heat pump on: {hp.is_on()}")
print(f"opmode:{hp.get_opmode_str()}")
print(f"cooling target: {hp.get_cooling_target()}{hp.temperature_units}")
print(f"heating target: {hp.get_heating_target()}{hp.temperature_units}")
print(f"dhw target: {hp.get_dhw_target()}{hp.temperature_units}")
print("-------Read Only---------")
print(f"ambient air temp: {hp.get_ambient_temp():.1f}{hp.temperature_units}")
print(f"inlet: {hp.get_inlet_temp()}{hp.temperature_units}")
print(f"outlet: {hp.get_outlet_temp()}{hp.temperature_units}")
print(f"dhw temp: {hp.get_dhw_temp()}{hp.temperature_units}")
print(f"defrosting: {hp.is_defrost()}")
print(f"compressor freq.: {hp.get_compressor_frequency()}hz")
print(f"E1: {hp.is_dhw_elec()}")
print(f"E2: {hp.is_aux_elec()}")
print(f"run mode: {hp.get_running_mode_str()}")
print(f"water flow: {hp.get_water_flow()}L/m")
print(f"water pump speed: {hp.get_water_pump_speed()}%")
print(f"current: {hp.get_input_current()}amps")
print(f"voltage: {hp.get_input_voltage()}volts")